<?php

namespace Database\Factories;

use App\Models\Dish;
use App\Models\Video;
use App\Models\VideoOrigin;
use App\Models\VideoStatus;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Video>
 */
class VideoFactory extends Factory
{
    protected $model = Video::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'dish_id' => Dish::factory(),
            'origin_id' => $this->originId('ia', 'IA'),
            'generation_id' => null,
            'status_id' => $this->statusId('processando', 'Processando'),
            'mux_asset_id' => null,
            'mux_playback_id' => null,
            'cover_path' => null,
            'duration_seconds' => null,
        ];
    }

    /**
     * Indicate that Mux finished processing and the video awaits the owner's approval.
     */
    public function awaitingApproval(): static
    {
        return $this->state(fn (array $attributes) => [
            'status_id' => $this->statusId('aguardando_aprovacao', 'Aguardando Aprovação'),
            'mux_asset_id' => 'asset_'.fake()->uuid(),
            'mux_playback_id' => 'playback_'.fake()->uuid(),
            'cover_path' => 'video-covers/'.fake()->uuid().'.jpg',
            'duration_seconds' => fake()->numberBetween(5, 15),
        ]);
    }

    /**
     * Indicate that the owner approved this video as the dish's active video.
     */
    public function approved(): static
    {
        return $this->awaitingApproval()->state(fn (array $attributes) => [
            'status_id' => $this->statusId('aprovado', 'Aprovado'),
        ]);
    }

    /**
     * Indicate that the owner rejected this video.
     */
    public function rejected(): static
    {
        return $this->awaitingApproval()->state(fn (array $attributes) => [
            'status_id' => $this->statusId('rejeitado', 'Rejeitado'),
        ]);
    }

    /**
     * Indicate that the video was uploaded by the owner directly, not generated by AI.
     */
    public function upload(): static
    {
        return $this->state(fn (array $attributes) => [
            'origin_id' => $this->originId('upload', 'Upload'),
            'generation_id' => null,
        ]);
    }

    private function statusId(string $slug, string $name): int
    {
        return VideoStatus::query()->firstOrCreate(['slug' => $slug], ['name' => $name])->id;
    }

    private function originId(string $slug, string $name): int
    {
        return VideoOrigin::query()->firstOrCreate(['slug' => $slug], ['name' => $name])->id;
    }
}
